server:
  port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:eureka-server}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: bus-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:rabbitmq}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
